


/**
 * Describes room level structure maximums and construction capabilities per level.
 * if a field is undefined, assume false or 0.
*/
const roomLevel = {

    0: {
        roads: true,    
        ramparts: false,
        walls: false,
        storage: false,
        numExtensions: 0,
        extensionCapacity: 0,
        numContainers: 5,
        numSpawns: 0,
    },
    1: {
        roads: true,
        ramparts: false,
        walls: false,
        storage: false,
        numExtensions: 0,
        numContainers: 5,
        numSpawns: 1
    }, 
    2:  {  
        roads: true,
        ramparts: true,
        walls: true,
        storage: false,
        numContainers: 5,
        numExtensions: 5,
        extensionCapacity: 50,
        rampartMaxHitpoints: 300000,
        numTowers: 0,
    },
    3: {
        roads: true,
        ramparts: true,
        walls: true,
        storage: false,
        numContainers: 5,
        numExtensions: 10,
        extensionCapacity: 50,
        rampartMaxHitpoints: 1000000,
        numSpawns: 1,
        numTowers: 1,
    },
    4: {
        roads: true,
        ramparts: true,
        walls: true,
        storage: true,
        numContainers: 5,
        numExtensions: 20,
        extensionCapacity: 50,
        rampartMaxHitpoints: 3000000,
        numSpawns: 1,
        numTowers: 1,
    },
    5: {
        roads: true,
        ramparts: true,
        walls: true,
        storage: true,
        numContainers: 5,
        numExtensions: 30,
        numSpawns: 1,
        numTowers: 2,
        numLinks: 2,
        extensionCapacity: 50,
        rampartMaxHitpoints: 10000000,

    },
    6: {
        roads: true,
        ramparts: true,
        walls: true,
        storage: true,
        extractor: true,
        terminal: true,
        numContainers: 5,
        numExtensions: 40,
        extensionCapacity: 50,
        rampartMaxHitpoints: 30000000,
        numSpawns: 1,
        numTowers: 2,
        numLinks: 3,
        numLabs: 3,
    },
    7: {
        roads: true,
        ramparts: true,
        walls: true,
        storage: true,
        extractor: true,
        terminal: true,
        factory: true,
        numContainers: 5,
        numExtensions: 50,
        extensionCapacity: 100,
        rampartMaxHitpoints: 100000000,
        numSpawns: 2,
        numTowers: 3,
        numLinks: 4,
        numLabs: 6,
    },
    8: {
        roads: true,
        ramparts: true,
        walls: true,
        storage: true,
        extractor: true,
        terminal: true,
        factory: true,
        observer: true,
        nuker: true,
        powerSpawn: true,
        numContainers: 5,
        numExtensions: 60,
        extensionCapacity: 200,
        rampartMaxHitpoints: 300000000,
        numSpawns: 3,
        numTowers: 6,
        numLinks: 4,
        numLabs: 10,
    }


}